export default [
  {
    id: "event1",
    title: "Group Yoga",
    date: "2025-05-17",
    time: "18:00 - 19:00",
    location: "@m/s Emma | Kauppatorin satama",
    description: "Join us for an evening of relaxing group yoga on the private cruise M/S Emma. Rejuvenate while enjoying scenic views.",
    image: "https://kanavansuuntelakka.fi/wp-content/uploads/2014/01/emma-23.jpeg",
  },
  {
    id: "event2",
    title: "Picnic",
    date: "2025-06-12",
    time: "12:00 - 15:00",
    location: "Kafe Coma, Tokoinranta | Elaintarhantie 12, 00530, Helsinki",
    description: "Enjoy a laid-back afternoon picnic by the waterfront with friends, games, and delicious food.",
    image: "https://cdn.siasat.com/wp-content/uploads/2023/03/Sunset-Cinema-Club-780x470.jpg",
  },
  {
    id: "event3",
    title: "Sleep Training",
    date: "2025-07-08",
    time: "10:00 - 11:30",
    location: "Hotel Common Room, Helsinki",
    description: "Learn techniques and tips to improve your sleep quality with certified trainers in this immersive sleep training workshop.",
    image: "https://miro.medium.com/v2/resize:fit:720/format:webp/0*eLP-8mjWU1ypPh2Q",
  },
  {
    id: "event4",
    title: "Wellness Training",
    date: "2025-04-25",
    time: "09:00 - 12:00",
    location: "Wellness Center, Helsinki",
    description: "A comprehensive wellness training session covering physical and mental health practices for a balanced lifestyle.",
    image: "https://kanavansuuntelakka.fi/wp-content/uploads/2014/01/emma-23.jpeg",
  },
  {
    id: "event5",
    title: "Mini Golf",
    date: "2025-08-20",
    time: "14:00 - 17:00",
    location: "Megazone Helsinki, Salomonkatu 15, Helsinki",
    description: "Challenge your friends in a friendly mini golf tournament and enjoy an afternoon of fun!",
    image: "https://cdn.siasat.com/wp-content/uploads/2023/03/Sunset-Cinema-Club-780x470.jpg",
  },
  {
    id: "event6",
    title: "Volleyball Match",
    date: "2025-06-21",
    time: "15:00 - 17:00",
    location: "Hietaniemi Beach, Helsinki",
    description: "Bring your team spirit for a beach volleyball match at Hietaniemi Beach!",
    image: "https://miro.medium.com/v2/resize:fit:720/format:webp/0*eLP-8mjWU1ypPh2Q",
  },
  {
    id: "event7",
    title: "Football Game",
    date: "2025-09-10",
    time: "18:00 - 20:00",
    location: "Oulunkylä Sports Park, Helsinki",
    description: "Join us for an exciting football game at Oulunkylä Sports Park.",
    image: "https://kanavansuuntelakka.fi/wp-content/uploads/2014/01/emma-23.jpeg",
  },
  {
    id: "event8",
    title: "Pilates Class",
    date: "2025-05-30",
    time: "11:00 - 12:00",
    location: "Yoga Studio Helsinki, Mikonkatu 15, Helsinki",
    description: "Start your day with an energizing pilates class at Yoga Studio Helsinki.",
    image: "https://cdn.siasat.com/wp-content/uploads/2023/03/Sunset-Cinema-Club-780x470.jpg",
  },
  {
    id: "event9",
    title: "Guided Meditation",
    date: "2025-06-05",
    time: "17:00 - 18:00",
    location: "Nature Reserve, Espoo",
    description: "Relax and unwind with a guided meditation session surrounded by nature.",
    image: "https://miro.medium.com/v2/resize:fit:720/format:webp/0*eLP-8mjWU1ypPh2Q",
  },
  {
    id: "event10",
    title: "Pottery Workshop",
    date: "2025-07-15",
    time: "13:00 - 16:00",
    location: "Art Studio, Helsinki",
    description: "Explore your creativity with hands-on pottery-making in this workshop for all skill levels.",
    image: "https://kanavansuuntelakka.fi/wp-content/uploads/2014/01/emma-23.jpeg",
  },
  {
    id: "event11",
    title: "Guest Speaker",
    date: "2025-09-12",
    time: "16:00 - 18:00",
    location: "Conference Center, Helsinki",
    description: "Listen to inspiring talks from guest speakers on various topics related to wellness and productivity.",
    image: "https://cdn.siasat.com/wp-content/uploads/2023/03/Sunset-Cinema-Club-780x470.jpg",
  },
  {
    id: "event12",
    title: "Karaoke Night",
    date: "2025-08-14",
    time: "20:00 - 23:00",
    location: "Karaoke Bar, Helsinki",
    description: "Show off your singing skills and enjoy a night of fun with friends at Karaoke Bar.",
    image: "https://miro.medium.com/v2/resize:fit:720/format:webp/0*eLP-8mjWU1ypPh2Q",
  }
];
