export default [
  {
    id: "event1",
    title: "Group Yoga",
    date: "2025-05-17",
    time: "18:00 - 19:00",
    location: "@m/s Emma | Kauppatorin satama",
    description: "Join us for an unforgettable evening of relaxing group yoga aboard the private cruise M/S Emma. Immerse yourself in a peaceful atmosphere as you rejuvenate your mind and body, guided by experienced instructors. While you stretch and unwind, enjoy stunning scenic views of the water, making it the perfect blend of tranquility and natural beauty.",
    image: "https://images.pexels.com/photos/14989453/pexels-photo-14989453/free-photo-of-photo-of-a-people-exercising-at-a-gym.jpeg?auto=compress&cs=tinysrgb&w=672",
  },
  {
    id: "event2",
    title: "Picnic",
    date: "2025-06-12",
    time: "12:00 - 15:00",
    location: "Kafe Coma, Tokoinranta | Elaintarhantie 12, 00530, Helsinki",
    description: "Enjoy a laid-back afternoon picnic by the serene waterfront, surrounded by the beauty of nature and the company of friends. Indulge in a variety of delicious food, from fresh snacks to hearty meals, while playing fun games and enjoying each other's company. Whether you're relaxing on a cozy blanket or soaking in the scenic views, this perfect afternoon promises great food, laughter, and lasting memories in a tranquil setting.",
    image: "https://images.pexels.com/photos/745045/pexels-photo-745045.jpeg?auto=compress&cs=tinysrgb&w=672&h=750&dpr=2",
  },
  {
    id: "event3",
    title: "Sleep Training",
    date: "2025-07-08",
    time: "10:00 - 11:30",
    location: "Hotel Common Room, Helsinki",
    description: "Learn techniques and tips to improve your sleep quality with certified trainers in this immersive sleep training workshop.",
    image: "https://images.pexels.com/photos/25956170/pexels-photo-25956170/free-photo-of-a-tiger-sleeping-in-a-zoo.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  // {
  //   id: "event5",
  //   title: "Mini Golf",
  //   date: "2025-08-20",
  //   time: "14:00 - 17:00",
  //   location: "Megazone Helsinki, Salomonkatu 15, Helsinki",
  //   description: "Challenge your friends to a friendly mini golf tournament and enjoy an exciting afternoon filled with fun and friendly competition. Test your skills on the course, navigating through creative obstacles while sharing laughs and good times. Whether you're aiming for a hole-in-one or just enjoying the game, it's the perfect way to spend a lively day outdoors with friends.",
  //   image: "https://images.pexels.com/photos/54123/pexels-photo-54123.jpeg?auto=compress&cs=tinysrgb&w=1200",
  // },
  // {
  //   id: "event6",
  //   title: "Volleyball Match",
  //   date: "2025-06-21",
  //   time: "15:00 - 17:00",
  //   location: "Hietaniemi Beach, Helsinki",
  //   description: "Bring your team spirit and join us for an exciting beach volleyball match at Hietaniemi Beach! Whether you're spiking, serving, or diving in the sand, it's the perfect opportunity to enjoy the outdoors while bonding with friends or colleagues. Feel the sun on your skin, the breeze in the air, and the thrill of friendly competition in this fun-filled match by the beach. Don't miss out on this action-packed day of sports and camaraderie!",
  //   image: "https://images.pexels.com/photos/6180408/pexels-photo-6180408.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  // },
  // {
  //   id: "event7",
  //   title: "Football Game",
  //   date: "2025-09-10",
  //   time: "18:00 - 20:00",
  //   location: "Oulunkylä Sports Park, Helsinki",
  //   description: "Join us for an exciting football game at Oulunkylä Sports Park! Whether you're a seasoned player or just looking to have some fun, this game promises plenty of action and team spirit. Enjoy the thrill of friendly competition in a vibrant, outdoor setting. It's the perfect opportunity to show off your skills, bond with teammates, and make lasting memories. Don't miss out on this high-energy game at one of the best sports parks in the area!",
  //   image: "https://images.pexels.com/photos/18026365/pexels-photo-18026365/free-photo-of-men-playing-soccer-match.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  // },
  // {
  //   id: "event8",
  //   title: "Pilates Class",
  //   date: "2025-05-30",
  //   time: "11:00 - 12:00",
  //   location: "Yoga Studio Helsinki, Mikonkatu 15, Helsinki",
  //   description: "Start your day with an energizing Pilates class at Yoga Studio Helsinki! Boost your energy, improve your flexibility, and strengthen your core with a series of dynamic exercises in a serene and welcoming environment. Led by experienced instructors, this class is designed to help you feel refreshed and revitalized, setting a positive tone for the rest of your day. Whether you're new to Pilates or an experienced practitioner, it's the perfect way to center yourself and embrace the day ahead with confidence.",
  //   image: "https://images.pexels.com/photos/868483/pexels-photo-868483.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  // },
  // {
  //   id: "event9",
  //   title: "Guided Meditation",
  //   date: "2025-06-05",
  //   time: "17:00 - 18:00",
  //   location: "Nature Reserve, Espoo",
  //   description: "Relax and unwind with a peaceful guided meditation session surrounded by the calming sounds of nature. Let go of stress as you immerse yourself in a tranquil outdoor setting, with each breath bringing you closer to inner calm. Led by an experienced instructor, this session will guide you through mindfulness techniques to clear your mind and restore balance. Whether you’re new to meditation or a seasoned practitioner, this serene experience is the perfect way to reconnect with yourself and the natural world around you.",
  //   image: "https://images.pexels.com/photos/6648552/pexels-photo-6648552.jpeg?auto=compress&cs=tinysrgb&w=1200",
  // },
  // {
  //   id: "event10",
  //   title: "Pottery Workshop",
  //   date: "2025-07-15",
  //   time: "13:00 - 16:00",
  //   location: "Art Studio, Helsinki",
  //   description: "Explore your creativity and unleash your artistic potential with a hands-on pottery-making workshop, designed for all skill levels. Whether you're a beginner or have some experience, this workshop offers personalized guidance to help you shape, mold, and design unique pottery pieces. Learn the techniques of wheel-throwing and hand-building while working with clay in a relaxed, supportive environment. It’s a fun and fulfilling way to express your creativity, connect with others, and take home your own handcrafted masterpieces.",
  //   image: "https://images.pexels.com/photos/3094225/pexels-photo-3094225.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  // },
  // {
  //   id: "event11",
  //   title: "Guest Speaker",
  //   date: "2025-09-12",
  //   time: "16:00 - 18:00",
  //   location: "Conference Center, Helsinki",
  //   description: "Listen to inspiring talks from expert guest speakers on a variety of topics related to wellness, productivity, and personal growth. Gain valuable insights on how to improve mental and physical health, boost your productivity, and achieve a balanced life. These thought-provoking sessions are designed to motivate and empower you with practical tips and strategies you can implement right away. Whether you're looking to enhance your well-being or improve your work-life balance, this event offers valuable knowledge to help you thrive in all areas of life.",
  //   image: "https://images.pexels.com/photos/3184328/pexels-photo-3184328.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  // },
  // {
  //   id: "event12",
  //   title: "Karaoke Night",
  //   date: "2025-08-14",
  //   time: "20:00 - 23:00",
  //   location: "Karaoke Bar, Helsinki",
  //   description: "Show off your singing skills and enjoy a night of fun with friends at Karaoke Bar! Belt out your favorite tunes, whether you're a seasoned performer or just looking to have a laugh. With a wide selection of songs to choose from, everyone can take the stage and be a star for the night. The lively atmosphere, great music, and supportive crowd will make for an unforgettable evening full of laughter, good vibes, and unforgettable memories. Grab the mic and get ready for an exciting night of music and fun!",
  //   image: "https://images.pexels.com/photos/18433815/pexels-photo-18433815/free-photo-of-woman-singing-with-microphone-on-party.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  // }
];
